attendance/urls.py
from django.urls import path
from . import views


app_name = 'attendance'


urlpatterns = [
    path('', views.attendance_redirect, name='attendance'),
    path('admin_leave/', views.admin_leave, name='admin_leave'),
    path('staff_attendance/', views.staff_attendance, name='staff_attendance'),
    path('chamcong/', views.chamcong, name='chamcong'),
]

funds/urls.py
from django.urls import path
from . import views

app_name = 'funds'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_funds/', views.add_funds, name='add_funds'),
    path('change_funds/<int:id>', views.change_funds, name='change_funds'),
    path('delete_funds/<int:id>', views.delete_funds, name='delete_funds'),
    path('transactions/', views.view_transactions, name='view_transactions'),
]

payroll/urls.py
from django.urls import path
from . import views

app_name='payroll'

urlpatterns = [
    path('view_salary/', views.view_salary, name='view_salary'),
    path('add_salary/', views.add_salary, name='add_salary'),
    path('view_history_salary/', views.view_history_salary, name='view_history_salary'),
    path('salary_payment/', views.salary_payment, name='salary_payment'),
    path('salary_payment/invoice/<int:payment_id>/', views.export_salary_invoice, name='export_salary_invoice'),
]

payroll_project/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index # Import view trang chủ từ App core

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # TRANG CHỦ (ROOT URL)
    path('', index, name='home'),

    # KẾT NỐI CÁC APP CON 
    path('users/', include('users.urls', namespace='users')),
    path('payroll/', include('payroll.urls', namespace='payroll')),
    path('attendance/', include('attendance.urls', namespace='attendance')),
    path('funds/', include('funds.urls', namespace='funds')),
    path('report/', include('report.urls', namespace='report')),
]

report/urls.py
from django.urls import path
from . import views

app_name = 'report'

urlpatterns = [
    path('', views.admin_reports, name='admin_reports'),
    path('salary_by_position/', views.salary_by_position, name='salary_by_position'),
    path('salary_payment_status/', views.salary_payment_status, name='salary_payment_status'),
    path('staff_observe/', views.staff_observe, name='staff_observe')
]

users/urls.py
from django.urls import path
from . import views

app_name='users'

# urlpatterns = [
#     path('login/', views.login_view, name='login'),
#     path('logout/', views.logout_view, name='logout'),
#     path('admin_dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
#     path('admin/add_staff', views.add_staff_view, name='add_staff'),
#     path('admin/list_staff', views.list_staff_view, name='list_staff'),
#     path('admin/delete_staff/<str:staff_id>', views.delete_staff_view, name='delete_staff'),
#     path('profile/', views.profile_view, name='profile'),
#     path('profile/edit', views.edit_profile_view, name='edit_profile'),
#     path('staff_dashboard', views.staff_dashboard, name='staff_dashboard')
# ]

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    # ADMIN FEATURES 
    path('admin/', views.admin_dashboard_view, name='admin_dashboard'),
    path('admin/staffs/', views.list_staff_view, name='list_staff'),
    path('admin/staffs/add/', views.add_staff_view, name='add_staff'),
    path('admin/staffs/delete/<str:staff_id>/', views.delete_staff_view, name='delete_staff'), 
    path('admin/staffs/edit/<str:staff_id>/', views.admin_edit_staff_view, name='admin_edit_staff'),

    # STAFF FEATURES 
    path('staff/', views.staff_dashboard, name='staff_dashboard'), 
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile_view, name='edit_profile'),
    path('profile/salary_history', views.salary_history_view, name='salary_history'),
    path('profile/leave_history', views.leave_history_view, name='leave_history'),
    path('profile/change_password', views.change_password_view, name='change_password'),

    path('leave_request/', views.leave_request, name='leave_request')

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Hệ thống Quản lý Lương{% endblock %}</title>
    <!-- Link CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block extra_css %}{% endblock extra_css %}
</head>
<body>
    <!-- Header/Navigation Bar -->
    <div class="header">
        <p style="margin:0;">PAYROLL SYSTEM | 
        </p>
    </div>

    <!-- Sidebar Area -->
    <div class="sidebar">
        {% block sidebar %}
            <!-- Menu mặc định:-->
            <a href="base_staff.html">Đăng nhập</a>
        {% endblock %}
    </div>

    <!-- Main Content Area -->
    <div class="content">
        {% block content %}
            
        {% endblock %}
    </div>
</body>
</html>

templates/base_admin.html
{% extends "base.html" %}

{% block sidebar %}
    <!-- <a href="base_admin.html">Dashboard Quản Trị</a> -->
    <a href="{% url 'users:admin_dashboard' %}">Dashboard Quản Trị</a>
    <hr style="border-top: 1px solid #555;">
    
    <a href="{% url 'users:list_staff' %}">Thêm/QL Nhân viên</a>
    <a href="{% url 'payroll:view_salary' %}">Bảng lương</a>
    <a href="{% url 'payroll:salary_payment' %}">Thanh toán lương</a>
    <a href="{% url 'attendance:admin_leave' %}">Duyệt Nghỉ Phép</a>
    <a href="{% url 'funds:index' %}">Quản Lý Tiền Quỹ</a>
    <a href="{% url 'report:admin_reports' %}">Báo Cáo Thống Kê</a>
    <hr style="border-top: 1px solid #555;">
    <!-- <a href="base_admin.html">Đăng xuất</a> -->
    <a href="{% url 'users:logout' %}">Đăng xuất</a>

{% endblock %}

{% block content %}
    {% block admin_content %}
        <h3>Chào Admin! Vui lòng chọn chức năng từ menu.</h3>
    {% endblock %}
{% endblock %}

templates/base_staff.html
{% extends "base.html" %}

{% block sidebar %}
    <a href="{% url 'users:staff_dashboard' %}">Trang chủ</a>
    <hr style="border-top: 1px solid #555;">

    <a href="{% url 'users:profile' %}">Hồ sơ cá nhân</a>
    <a href="{% url 'users:salary_history' %}">Lịch sử Trả lương</a>
    <a href="{% url 'users:leave_history' %}">Lịch Nghỉ & Công</a>
    <a href="{%url 'users:change_password' %}">Đổi mật khẩu</a>
    <a href="{% url 'users:leave_request' %}">Xin nghỉ phép</a>
    <a href="{% url 'report:staff_observe' %}">Theo dõi chấm công</a>
    <hr style="border-top: 1px solid #555;">
    <a href="{% url 'users:logout' %}">Đăng xuất</a>
{% endblock %}

{% block content %}
    {% block staff_content %}
        <h3>Bạn có thể tra cứu thông tin cá nhân và lịch sử làm việc ở menu bên trái.</h3>
    {% endblock %}
{% endblock %}